### ISSUE TITLE
Bug: could not run extension using vscode settings setup

### ISSUE THREAD

**Issue by dmitry-prohorov** [no-stack-dub-sack/apexdox-vs-code#12]
Could not run `> ApexDox: Run` command from vscode using `settings.json` setup. Getting next exception 
![image](https://user-images.githubusercontent.com/11081166/71320885-fc196700-24c2-11ea-986d-611137111891.png)

### Workaround: use`.apexdoxrc` or `apexdox.yaml` files for setup.
Vscode+System
```
Version: 1.41.1
Commit: 26076a4de974ead31f97692a0d32f90d735645c0
Date: 2019-12-18T14:57:51.166Z
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.0.0
```
Stack trace:
```console
notificationsAlerts.ts:40 'isExtensible' on proxy: trap result does not reflect extensibility of proxy target (which is 'true')
onDidNotificationChange @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:581
addNotification @ notifications.ts:171
notify @ notificationService.ts:101
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
(anonymous) @ rpcProtocol.ts:101
fire @ event.ts:581
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:581
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:200
addChunk @ _stream_readable.js:294
readableAddChunk @ _stream_readable.js:275
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] TypeError: 'isExtensible' on proxy: trap result does not reflect extensibility of proxy target (which is 'true')	at l.validate (/Users/d-pro/.vscode/extensions/peterweinberg.apexdox-vs-code-1.0.2/dist/extension.js:1:353479)	at Function.getConfig (/Users/d-pro/.vscode/extensions/peterweinberg.apexdox-vs-code-1.0.2/dist/extension.js:1:219139)	at /Users/d-pro/.vscode/extensions/peterweinberg.apexdox-vs-code-1.0.2/dist/extension.js:32:189974	at v._executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:538:925)	at v.$executeContributedCommand (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:539:295)	at p._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:663:275)	at p._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:662:971)	at p._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:661:639)	at p._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:660:468)	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:658:691	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)	at _.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189:274)	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:820:285	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)	at _.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:189:274)	at t.PersistentProtocol._receiveMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:193:629)	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:190:824	at l.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:46:893)	at p.acceptChunk (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:737)	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:186:89	at Socket.t (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:195:68)	at Socket.emit (events.js:200:13)	at addChunk (_stream_readable.js:294:12)	at readableAddChunk (_stream_readable.js:275:11)	at Socket.Readable.push (_stream_readable.js:210:10)	at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
```

**Comment by no-stack-dub-sack** [comment]
@dmitry-prohorov Sorry for the delay (holiday season here, been away from my computer most of the week), and thanks for raising this issue. I will look into this. Everything, of course, was working on earlier versions of VS Code, at least on Windows. I will try to replicate this up to the point that I can and try to narrow down the cause.

Glad you were able to find a workaround in the meantime.

**Comment by no-stack-dub-sack** [comment]
Thanks again for bringing this to my attention. #13 closes this issue, and I have made a patch release to address this.
